GET http://localhost:3001/

###
# @name login
POST http://localhost:3001/login
Accept: "application/json"


{
    "username":"fbanna",
    "password":"shta2telik"
}

###
@authToken={{login.response.headers.X-Authtoken}}
GET http://localhost:3001/?auth={{authToken}}
Accept: application/json
Authorization: Bearer {{authToken}} 

{
    "auth":"{{authToken}}"
}

###
@authToken={{login.response.headers.X-Authtoken}}
POST http://localhost:3001/logout
Accept: application/json
Authorization: Bearer    {{authToken}}

